#!/bin/sh

alias dotfiles="/usr/bin/git --git-dir='$HOME/.dotfiles/' --work-tree='$HOME'"
alias lf=lfub
alias lfub="$HOME/.local/bin/lf/lfub"
alias mpva="mpv --no-audio-display --no-video --volume=50"

ytm () {
    [ -z "$1" ] && echo "No argument supplied" && return;
    mpva --ytdl-format=bestaudio "ytdl://ytsearch:$*"
}

ytpl () {
    yt-dlp -x -f bestaudio/best -o "%(track,title)s.%(ext)s" --extractor-args "youtube:lang=en" \
        --embed-thumbnail --add-metadata --embed-metadata \
        --cookies-from-browser "firefox:/home/$USER/.librewolf" \
        --parse-metadata "playlist_index:%(track_number)s" "$*"
}

mkcd ()
{
    mkdir -p -- "$1" &&
       cd -P -- "$1"
}

[ -x "$(command -v nvim)" ] && alias vim="nvim"

for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt-dlp -x -f bestaudio/best" \
	ytt="yt-dlp --skip-download --write-thumbnail" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

