#!/bin/bash

# Check for drives.
lsblkoutput="$(lsblk -rpo "uuid,name,type,size,label,mountpoint,fstype")"

# Functioning for formatting drives correctly for wmenu:
filter() { sed "s/ /:/g" | awk -F':' '$7==""{printf "%s%s (%s) %s\n",$1,$3,$5,$6}' ; }

# Get all normal, non-encrypted or decrypted partitions that are not mounted.
normalparts="$(echo "$lsblkoutput"| grep 'part\|rom\|crypt' | sed "s/^/💾 /" | filter )"

# Add all to one variable. If no mountable drives found, exit.
alldrives="$(echo "$normalparts" | sed "/^$/d;s/ *$//")"

# Quit the script if a sequential command fails.
set -e

test -n "$alldrives"

# Feed all found drives to wmenu and get user choice.
chosen="$(echo "$alldrives" | wmenu -p "Mount which drive?" -i)"

# Function for prompting user for a mountpoint.
getmount(){
	mp="$(find /mnt /media /mount -maxdepth 1 -type d 2>/dev/null | wmenu -i -p "Mount this drive where?")"
	test -n "$mp"
	if [ ! -d "$mp" ]; then
		mkdiryn=$(printf "No\\nYes" | wmenu -i -p "$mp does not exist. Create it?")
		[ "$mkdiryn" = "Yes" ] && (mkdir -p "$mp" || sudo -A mkdir -p "$mp")
	fi
}

attemptmount(){
		# Attempt to mount without a mountpoint, to see if drive is in fstab.
		sudo -A mount "$chosen" || return 1
		notify-send "💾Drive Mounted." "$chosen mounted."
		exit
}

case "$chosen" in
	💾*)
		chosen="${chosen%% *}"
		chosen="${chosen:1}"	# This is a bashism.
		parttype="$(echo "$lsblkoutput" | grep "$chosen")"
		attemptmount || getmount
		case "${parttype##* }" in
			vfat) sudo -A mount -t vfat "$chosen" "$mp" -o rw,umask=0000 ;;
			btrfs|ext4) sudo -A mount "$chosen" "$mp" ;;
			ntfs) sudo -A mount -t ntfs3 "$chosen" "$mp" ;;
			*) sudo -A mount "$chosen" "$mp" -o uid="$(id -u)",gid="$(id -g)" ;;
		esac
		notify-send "💾Drive Mounted." "$chosen mounted to $mp."
		;;
esac
